name: Test and build Application 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  GAR_LOCATION: us-central1
  SERVICE: YOUR_SERVICE_NAME
  REPOSITORY: deployment-react

  # --- Add GKE Cluster Info ---
  GKE_CLUSTER:  my-first-cluster-1
  GKE_LOCATION: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: setup nodeJs
      #setup nodeJs
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
            
      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Authenticate with gcp
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
      
      - name: use gcloud sdk
        run: gcloud info

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/dep-react
          tags: |
            # Tag with the Git branch name (e.g., 'main')
            type=ref,event=branch
            # Tag with the full Git commit SHA (e.g., 'sha256:...')
            type=sha,format=long
        
      - name: define tag v2
        id: define-tag
        run: |
          TAG_NAME=""
          if [ ${{ github.event_name }} == 'pull_request' ] ; then
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
            echo "TAG_NAME=PR-${{ github.event.pull_request.number }}-$(date +%Y%m%d%H%M)-${HEAD_SHA:0:8}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[\/_ @]/-/g')-$(date +%Y%m%d%H%M)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: LOG docker tag ENV 2
        run: 'echo "Generated tags 2 ENV: ${{ env.TAG_NAME }}"'
        
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory as build context
          push: true # Push the image to the registry
          #tags: ${{ steps.meta.outputs.tags }} # Use tags generated by metadata action
          tags: | 
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/dep-react:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }} # Add labels generated by metadata action
          cache-from: type=gha # Enable GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max
      
      #K8S 
      - name: Get GKE Credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}
      
      - name: Substitute Image Tag in Deployment Manifest
        run: |
          echo "Substituting image tag with: ${{ env.TAG_NAME }}"
          # Use sed to replace the placeholder tag in the deployment file
          # Note the use of a different delimiter (#) for sed in case tags contain slashes
          sed -i "s#image: us-central1-docker.pkg.dev/.*/dep-react:placeholder-tag#image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/dep-react:${{ env.TAG_NAME }}#" devops/k8s/deployment.yaml
          echo "--- Patched deployment.yaml ---"
          cat devops/k8s/deployment.yaml # Print the patched file for verification
          echo "--- End Patched deployment.yaml ---"
      
      - name: Deploy to GKE
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f devops/k8s/
          # Optional: Wait for deployment rollout to complete
          # echo "Waiting for deployment rollout..."
          # kubectl rollout status deployment/static-react-app-deployment --timeout=5m
    

        