name: Test and build Application 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          # Required for SonarCloud analysis of PRs
          # Fetches Git history needed to identify changed files
          fetch-depth: 0
      - name: setup nodeJs
      #setup nodeJs
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
            
      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Authenticate with gcp
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:  
         python-version: '3.9'
      
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
      
      - name: 'use gcloud sdk'
        run: 'gcloud info'
      
      # - name: install the gcloud cli
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: ${{ secrets.GOOGLE_PROJECT }}
      #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #     export_default_credentials: true

          
    

        