name: Test Application # Corrected typo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4
        with:
          # Required for SonarCloud analysis of PRs
          # Fetches Git history needed to identify changed files
          fetch-depth: 0

      # Add caching for npm dependencies
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm # Cache the npm cache directory
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Optional: Add with args if needed for specific SonarCloud project config
        # with:
        #   args: >
        #     -Dsonar.organization=your-org-key
        #     -Dsonar.projectKey=your-project-key