name: Test Application # Corrected typo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4
        with:
          # Required for SonarCloud analysis of PRs
          # Fetches Git history needed to identify changed files
          fetch-depth: 0
      - name: setup nodeJs
      #setup nodeJs
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
            
      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
